In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

# NORMAL (50 rows)
normal = pd.DataFrame({
    "Temp": np.random.uniform(36.2, 37.2, 50),
    "Flex": np.random.uniform(200, 350, 50),
    "Heart": np.random.uniform(300, 450, 50),
    "Motion": np.random.choice([1], 50),
    "Label": "NORMAL"
})

# STRESS (50 rows)
stress = pd.DataFrame({
    "Temp": np.random.uniform(37.5, 38.5, 50),
    "Flex": np.random.uniform(400, 650, 50),
    "Heart": np.random.uniform(550, 750, 50),
    "Motion": np.random.choice([0], 50),
    "Label": "STRESS"
})

# CRITICAL (50 rows)
critical = pd.DataFrame({
    "Temp": np.random.uniform(39.0, 40.5, 50),
    "Flex": np.random.uniform(700, 950, 50),
    "Heart": np.random.uniform(850, 1023, 50),
    "Motion": np.random.choice([0], 50),
    "Label": "CRITICAL"
})

# Combine
dataset = pd.concat([normal, stress, critical])

# Save to CSV
dataset.to_csv("health_dataset_150.csv", index=False)

print("Dataset created successfully!")
dataset.head()


Dataset created successfully!


Temp        Flex       Heart  Motion   Label
0  36.574540  345.437694  304.714378       1  NORMAL
1  37.150714  316.269924  395.461562       1  NORMAL
2  36.931994  340.924841  347.153397       1  NORMAL
3  36.798658  334.224103  376.285604       1  NORMAL
4  36.356019  289.684997  436.134971       1  NORMAL

In [ ]:
from google.colab import files
files.download("health_dataset_150.csv")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

# Load dataset
data = pd.read_csv("health_dataset_150.csv")

# Separate features and labels
X = data[['Temp','Flex','Heart','Motion']]
y = data['Label']

# Encode labels
y = y.map({'NORMAL':0, 'STRESS':1, 'CRITICAL':2})

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train neural network
model = MLPClassifier(hidden_layer_sizes=(4,), max_iter=3000, random_state=42)
model.fit(X_scaled, y)

# Accuracy
print("Training Accuracy:", model.score(X_scaled, y))

# Print weights
print("\nHidden Layer Weights:")
print(model.coefs_[0])

print("\nHidden Layer Biases:")
print(model.intercepts_[0])

print("\nOutput Layer Weights:")
print(model.coefs_[1])

print("\nOutput Layer Biases:")
print(model.intercepts_[1])


Training Accuracy: 1.0

Hidden Layer Weights:
[[-0.64627854  1.35012452  0.38049094 -0.09767779]
 [-1.02127462  0.01550401 -0.68456972  0.34745429]
 [-0.26233529  0.94512312 -0.69148197  0.53500565]
 [ 1.02046191 -0.28544181 -1.14261279 -0.22470782]]

Hidden Layer Biases:
[ 0.08624207 -0.16990509  0.44856484 -0.68524877]

Output Layer Weights:
[[ 0.6768083  -1.16266294 -0.83854118]
 [-0.86106581 -0.71340312  1.15894407]
 [-0.7475175   1.05793562 -0.54742752]
 [-1.22839587 -0.08761272 -0.31957677]]

Output Layer Biases:
[-0.57820186  1.34006706  0.2703268 ]


In [ ]:
print("Means:", scaler.mean_)
print("Std Dev:", scaler.scale_)


Means: [3.81163051e+01 5.44827181e+02 6.54380313e+02 3.33333333e-01]
Std Dev: [  1.28669205 237.59713888 236.7084626    0.47140452]
